DROP TABLE IF EXISTS product_category CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS purchase CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS price_change CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS user_service CASCADE;